apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: frontend-ui
        image: frontend-ui:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: AUTH_URL
          value: http://auth-service:5001
        - name: BACKEND_URL
          value: http://backend-service:8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: task-app
spec:
  selector:
    app: frontend-ui
  ports:
    - port: 80
      targetPort: 5000