name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Docker metadata
      id: auth
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ secrets.DOCKER_USERNAME }}/py3tier
        tags: |
           type=raw,value=latest,enable={{is_default_branch}}
           type=sha,format=long,prefix=,enable=true

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
          context: ./auth-service
          file: ./auth-service/Dockerfile                # change if your Dockerfile is elsewhere
          push: true
          tags: ${{ steps.auth.outputs.tags }}
          labels: ${{ steps.auth.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

    - name: Extract Docker metadata
      id: front
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ secrets.DOCKER_USERNAME }}/py3tierfront
        tags: |
           type=raw,value=latest,enable={{is_default_branch}}
           type=sha,format=long,prefix=,enable=true

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
          context: ./frontend-ui
          file: ./frontend-ui/Dockerfile                # change if your Dockerfile is elsewhere
          push: true
          tags: ${{ steps.front.outputs.tags }}
          labels: ${{ steps.front.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

    - name: Extract Docker metadata
      id: back
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ secrets.DOCKER_USERNAME }}/py3tierback
        tags: |
           type=raw,value=latest,enable={{is_default_branch}}
           type=sha,format=long,prefix=,enable=true

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
          context: ./backend-api
          file: ./backend-api/Dockerfile                # change if your Dockerfile is elsewhere
          push: true
          tags: ${{ steps.back.outputs.tags }}
          labels: ${{ steps.back.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
